variables:
- group: mlops-init-dev
trigger:
- none
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: RunDeployPipeline
  displayName: Run Online Deploy Pipeline
  jobs:
    - job: DeployOnlineEndpoint
      timeoutInMinutes: 60
      steps:
      - checkout: self
        path: s/ #Source folder
      - template: /ado/tasks/install_az_cli.yml
      - template: /ado/tasks/install_aml_cli.yml
      - template: /ado/tasks/aml_workspace_connect.yml
      - template: /ado/tasks/aml_create_environment.yml
        parameters:
          build_type: conda
          environment_name: $(environment_serve_name)
          environment_file: aml/environment/serve_env.yml
      - template: /ado/tasks/aml_create_endpoint.yml
        parameters:
          endpoint_type: $(endpoint_type)
          endpoint_name: $(online_endpoint_name)
          endpoint_file: aml/src/definitions/serve/online_endpoint.yml
      - template: /ado/tasks/aml_create_deployment.yml
        #Deploy the online endpoint
        parameters:
          deployment_name: $(online_deployment_name)
          endpoint_name: $(online_endpoint_name)
          endpoint_type: $(endpoint_type)
          deployment_file: aml/src/definitions/serve/online_deployment.yml
          deployment_instance_sku: $(online_deployment_sku)
      
