steps:
  - task: AzureCLI@2
    displayName: Install AML CLI v2
    inputs:
      azureSubscription: $(aml_service_connection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e
        az version
        az extension add -n ml -y
        az extension update -n ml
        az extension list