pr: none
trigger: none
pool:
  vmImage: 'ubuntu-latest'
variables:
- group: mlops-terraform-state-dev
steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Delete tfstate resource group'
  inputs:
    azureSubscription: $(mlops_subscription)
    action: 'DeleteRG'
    resourceGroupName: $(tf_state_rg)
    location: $(tf_state_location)